apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-service-a-service-b
spec:
  podSelector:
    matchLabels:
      app: service-a
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: service-b
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
